[package]
name = "libatbus-binding-c"
version = "0.1.0"
authors = ["owent <admin@owent.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.*"
