site_name: libatbus-rs
docs_dir: src
# nav:
#   - Home: 'README.md'
#   - Document: index.md
repo_url: https://github.com/atframework/libatbus-rs
theme:
  name: material
  palette:
    scheme: slate
  locale: zh
  features:
    - toc.integrate
  highlightjs: true
  hljs_languages:
    - yaml
    - bash
    - cpp
    - bash
    - markdown
    - asciidoc
    - latex
    - xml
    - json
    - cmake
    - rust
    - go
    - diff
    - ini # TOML
    - javascript
    - typescript
    - protobuf
# extra_css:
#   - css/extra.css
#   - css/second_extra.css
# extra_javascript:
#   -
#   -
markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - offline:
      enabled: !ENV [OFFLINE, false]
  - awesome-pages
  # - optimize:
  #     enabled: !ENV [CI, false]
# collapse_single_pages: true
